### ISSUE TITLE
encryption seem to change not only the payload

### ISSUE THREAD

**Issue by bnorbs** [iwanders/plainRFM69#14]

**Comment by bnorbs** [comment]
For a sort of authentication I wanted to use a different AES Key for each node. On the hub / gateway side I planned to do encryption/decryption on the host. Therefore I would need to have encryption turned on one side and turned off at the other side. However, I cannot receive anything when encryption is off (and sender used it). Playing with promiscuous mode, revealed that also the node address was changed. I thought that encryption is only applied to the payload and not to the address byte, the length byte (if any) and to the crc bytes. I remember that I saw a drawing like that, but don't know where (Semtech?).
Could you give some insight waht happens here and why?
Tx, bnorbs

**Comment by iwanders** [comment]
Hey @bnorbs, the length and crc are definitely not encrypted. Please read through [check_crypto_mode](https://github.com/iwanders/plainRFM69/blob/master/extras/check_crypto_mode.py), it should provide you with some context how / where the encryption fits in.

See also page 55 of [the datasheet](https://cdn.sparkfun.com/datasheets/Wireless/General/RFM69HCW-V1.1.pdf);
> In Variable length mode the Max message size that can be encrypted/decrypted is also 64 bytes when address filtering is
disabled, else it is 48 bytes. Thus, including length byte, the length of the payload is max 65 or 50 bytes (the latter when
address filtering is enabled).

So 48 bytes when address filtering is enabled, so that means an entire 16 byte block is wasted / lost on the address byte when encryption is enabled.

The Python script I mentioned does describe how I sent that data from one side and received it on the other side, I don't think I tried it with addressing, because losing 25% of my available payload to a single byte sounded bad. This script also shows that the radio chip uses [ECB](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_codebook_(ECB)) as the cipher mode, which makes it pretty ineffective and not worth using if you can't fit your nonce + payload within 16 bytes.

My advice is to not use the encryption the chip offers, instead encrypt your data on your microcontroller and gateway, that way you are in charge of it completely. It also you to implement authentication and a nonce to guard against replay attacks. For more information on this, for example, look into [authenticated encryption](https://en.wikipedia.org/wiki/Authenticated_encryption) scheme's and message authentication codes ([HMAC](https://en.wikipedia.org/wiki/HMAC)).

**Comment by bnorbs** [comment]
Hi iwanders,
thanks for the insight. I think the best way is, to not use encryption build into rfm69, as you suggest. It is a bit of a shame that it is implemented that bad. I did notice that they only use ECB, but thought that I could "correct" that flaw by introducing some random number at the beginning of each 16 bytes block. Of course that would waste another 25% of the payload, on the other hand we would need to transfer a salt or IV. I hoped to add encryption & authentication even when using some older 8-Bit MCUs. Now I need to add another chip like Atmel ATECC508A or 608A or NXP SE050. Anyway,
thanks again -- bnorbs
