### ISSUE TITLE
RFM69HW

### ISSUE THREAD

**Issue by bloever** [iwanders/plainRFM69#2]
Hello again,

Do you have any examples for the RFM69HW version using PA1 and PA2 amplifiers? 

I have been using the following code, but I'm unsure if this actually activates the high-power mode.

Thanks agin for a great library, I have been using it daily!

``` c
rfm.setPALevel(RFM69_PA_LEVEL_PA1_ON | RFM69_PA_LEVEL_PA2_ON, 31); 
rfm.setOCP(0);
```

**Comment by iwanders** [comment]
Hi Bloever,

I only have the RFM69CW versions to test with, so I have no way to test this. But I can comment by reading the datasheet, you are on the right track but you missed setting the 'test' registers, which are actually required for the 20 dB power mode.

See page 22, Table 11 of the RFM69HW datasheet, it lists the values for RegTestPa1 and RegTestPa2 in case you want the high power transmissions. I'm not sure why they are called test registers, perhaps the 20 dB power mode is only a 'leftover' from testing? Anyways, I think the full code to enable the high power transmissions would become:

``` c
rfm.setPALevel(RFM69_PA_LEVEL_PA1_ON | RFM69_PA_LEVEL_PA2_ON, 31); 
rfm.setOCP(0);
rfm.setPa13dBm1(true);
rfm.setPa13dBm2(true);
```

In case you have one of those software defined radio DVB-T receivers you should actually be able to see the increase in power. I also used one of those when writing the library, very handy to see the effects of properties. The RSSI signal should also change on the receiving node, perhaps that's a way of testing whether it works, although I'm unsure whether the RSSI measurement is fast enough.

By the way, it might be interesting for other Moteino users if you would report your findings and board modifications for use with this library in a post on the Moteino forum. Anyways, it's great to hear that you are using the library and like it, thanks!

**Comment by bloever** [comment]
Hello again,

I believe it works with the commands you suggested. I was able to measure with a seperate Moteino that the RSSI changed from around -60 without the commands, to -30 RSSI once enabled. RSSI numbers was even lower (-25) with the RadioHead library, but that could probably also be down to how the RSSI calculation is done. 

I'll create a thread on the Moteino forums eventually to let others know that there is an alternative to RFM69/RadioHead. (I searched for quite some time before I found this).

Thanks again for taking the time to respond to my questions.

**Comment by iwanders** [comment]
The difference in RSSI can be due to many things, I also noticed some things about this when I wrote the library. It's some time ago, so don't pin me down on the following.

I believe it mattered where in your code you performed the RSSI measurement. I did some digging in my (private) development repository, there I found the following note (from November 2014): 'SSI is reset when RFM69_AUTOMODE_INTERMEDIATEMODE_SLEEP is used, RFM69_AUTOMODE_INTERMEDIATEMODE_STANDBY prevents that issue, but RSSI seems to be about 10 higher... weird.', so just switching to another mode when leaving Rx mode changes the value in the RSSI register. Another log shows that in one instance after a packet was received where the first call of `getRssiValue()` value returned 54, the second call returns 0, then the FIFO is read, after which the third call returns 255. I don't know what the best practice is here, you will have to do some expirimentation to get a consistent value.

Additionally; this library configures the radio module such that it _itself_ starts the transmission only when there are bytes to be sent and disables Tx immediately after the packet is sent. This is different from the other libraries where the Tx mode is enabled and disabled by the MCU. If I'm not mistaken the radio module emits a carrier wave when it is in Tx mode but no data is available to be sent. If the Tx mode is disabled by the MCU, there is a (very?) small delay between finishing the transmission and disabling the Tx mode, which might result in a short duration when the carrier wave is being emitted after the packet is complete. The RSSI of the carrier wave will be higher than the signal with data is modulated on top of it, this might explain the difference in RSSI after receiving a packet. From the datasheet (section 3.4.9 of RFM69CW): 'RSSI: Its acquisition time is very short, taking only 2 bit periods.', perhaps the short part of the carrier wave after the packet is long enough to affect the RSSI? I would not really know of a way on how to verify this though.

If you want a better reading, you could try to force one of the radio's to transmit a carrier wave. You probably have to consult the datasheet if you want to try this, I found the following bit of code commented out somewhere:

``` c
rfm->setMode(RFM69_MODE_SEQUENCER_OFF | RFM69_MODE_STANDBY);
rfm->startRfCalibration();
while (rfm->completedRfCalibration() == false){
}
rfm->setMode(RFM69_MODE_SEQUENCER_OFF | RFM69_MODE_TRANSMITTER);
```

first disable the sequencer and put the radio into standby, calibrate it and then with the sequencer disabled switch it to transmitter mode. I haven't tested this, but it sounds right from what I remember, also not entirely sure why the calibration is required, perhaps just the last line also works. Consider that this will continuously emit a carrier wave at the frequency specified, you might exceed the legally set duty-cycle limitations on the ISM bands.

Glad to hear that the code for the RFM69HW increased transmission power looks like it's working.

**Comment by bloever** [comment]
Hello, 

Thanks for the detailed feedback. As you said the calculation can be impacted by a lot of things. I have tried to do the calculation in different places in the code. I'm currently performing the RSSI reading in the interrupt function where rfm.poll() is located. No real difference I can measure for now. 

Right after the rfm.poll() I'm doing the following:

``` c
int16_t _LAST_RSSI = 0;
_LAST_RSSI = -rfm.getRssiValue();
_LAST_RSSI >>= 1;
```

This is a graph of the RSSI values measured on a sending RFM69HW placed about 20 meters away between a few concrete walls. Interval is 10 minutes and the packet size is 28 bytes.
![graph](https://cloud.githubusercontent.com/assets/3875679/10465181/c8545ed4-71ed-11e5-829e-373ded27fcf5.PNG)

I have not tested the calibration yet. I'll try it out once I have to do some other updates on it as well. Do you have any experience with `rfm->startRfCalibration();` in changing temperatures? Will it have any sort of impact on the range? I'm currently down to 5-6 degrees celsius during the night and 12-17 during daytime. As winter aproaches this will also change even more. 

Thanks!

**Comment by iwanders** [comment]
The calibration does not matter to the RF part of the module, I checked the datasheet and the calibration only matters for the internal RC oscillator used for the listen modes. This was wrongfully named, I fixed this.

I have added a method which makes the radio module emit a continuous preamble. This might be helpful for your testing in regard to the signal strength. You might get better or worse transmissions if you orientate the antenna differently. To continuously emit the preamble, do the usual setup and then in place of sending a packet use the following to emit the preamble:

``` c
rfm->emitPreamble();
while(true){};
```

I tried to look up in the datasheet how to perform a proper RSSI measurement, but I could not really find anything on that. The `completedRssi` method never returns true, even when going into standby mode (which should disable the automatic RSSI measurements) and starting it by hand with `startRssi`. Conclusion; using the value returned by the `getRssiValue` method as you did is probably fine.

I moved the `getRssiValue` call around in the code in order to see whether that results in a different value. It does not, so perhaps only the mode to which you switch after a packet is received changes it. However, my readings when receiving a real packet (modified MinimalInterrupt example) were around -31 dB, whereas my readings with the `emitPreamble` were -27 dB with the distance between the receivers (about 30cm). I also did some test through walls and on longer range, the values you report with the graph are roughly what I would expect based on my tests. The RSSI value is returned in 0.5 dB increments, so while dividing it by two gives the number in dB you also lose some precision.

If you want more range you can try to lower the baudrate, this usually makes transmissions more reliable, the lowest I calculated the values for is `baud4800` but the radio can go lower. Additionally you can attempt to use a lower value for `setRSSIThreshold`, if there's little noise in your area you might be able to receive lower strength signals successfully. Perhaps you can find some values from someone else who tried to get as much range as possible.

(Slightly off-topic; if you use encryption there is no difference in transmission length between sending 28 bytes or sending 32 bytes, it is zero-padded to 16 byte multiples.)

**Comment by EtherFidelity** [comment]
FYI, I just submitted a pull request that adds high-power module support.

**Comment by iwanders** [comment]
I'm closing this, ticket has been inactive for more than 3 years and @etherfi  has just contributed proper support for the high power modules that's now merged into `master`.
